### ISSUE TITLE
Produce GraphQL Foundation Annual Report

### ISSUE THREAD

**Issue by caniszczyk** [graphql/foundation#17]
Produce the first annual report to celebrate our 1 year anniversary in March 2020!

**Comment by caniszczyk** [comment]
https://foundation.graphql.org/annual-report-2019/

Thanks @brianwarner for getting this out the door

**Comment by benjie** [comment]
This page worked on Thursday but is broken now 😱

**Comment by brianwarner** [comment]
Hi @benjie, can you please check this link instead? https://foundation.graphql.org/reports/annual-report-2019/

Also, I can easily add an alias so that this link resolves.  PR coming shortly...

**Comment by benjie** [comment]
That link works, but it’s not the one in Lee’s tweet ;)

**Comment by brianwarner** [comment]
Ah, I hadn't realized that link went out in a tweet :-) Just merged yesterday's PR, should be fixed!

Please let me know if any other issues pop up, and thanks for the heads up on this one.

**Comment by benjie** [comment]
Currently it's a redirect to `https://graphql.dev/reports/annual-report-2019/`

```
$ curl -iL https://foundation.graphql.org/annual-report-2019/
HTTP/2 200 
cache-control: public, max-age=0, must-revalidate
content-length: 337
content-type: text/html; charset=UTF-8
date: Mon, 06 Apr 2020 09:00:20 GMT
etag: "2d29e07eaebda50172f3d4cad716b212-ssl"
strict-transport-security: max-age=31536000
age: 0
server: Netlify
x-nf-request-id: 17f9a5b9-7066-45cb-b435-6e7392b76e55-9167416

<!DOCTYPE html><html><head><title>https://graphql.dev/reports/annual-report-2019/</title><link rel="canonical" href="https://graphql.dev/reports/annual-report-2019/"/><meta name="robots" content="noindex"><meta charset="utf-8" /><meta http-equiv="refresh" content="0; url=https://graphql.dev/reports/annual-report-2019/" /></head></html>
```

Which gives an SSL error:

![Screenshot_20200406_095919](https://user-images.githubusercontent.com/129910/78541444-8aed8d80-77ed-11ea-8f7f-fa67a507200e.png)

**Comment by brianwarner** [comment]
Hi @benjie , I was seeing the same error this morning with the SSL cert (for anything graphql.dev, it seemed), but don't any longer.  Has it resolved for you?

**Comment by benjie** [comment]
Works fine for me now! I'd say you can close this but it's already closed :wink:
