### ISSUE TITLE
Contribute to GraphQL Foundation September Newsletter 

### ISSUE THREAD

**Issue by mayaptos** [graphql/foundation#31]
Thanks to everyone for their contributions to the August newsletter https://foundation.graphql.org/news/2020/09/11/graphql-foundation-monthly-newsletter-august-2020/

We are now taking contributions for the September newsletter. Feel free to add directly to this doc here https://docs.google.com/document/d/10OG6nYp9TYKCs35FbcArEx426E6rYiRyzqOSiKzOey4/edit#

**Comment by benjie** [comment]
I've added:

> ### Querying Query query queries: "query" ambiguity
>
> Benjie first raised the issue of the ambiguity of the term "query" as used in the GraphQL spec and ecosystem back in April. In just this title, we've referred to requesting, the Query type, a query operation, and a nested selection set; but that's just some of the ways we use this term, which can make it really hard for people new to GraphQL to get up to speed. Benjie has analyzed the use of the term, and has proposed a consistent set of terminology to use based on other terms used in the GraphQL spec already, to be discussed at the next Working Group. See Spec PR #777.

**Comment by mayaptos** [comment]
Thanks @benjie. 

@acao @Urigo @IvanGoncharov Anything to add? Here's the initial issue https://github.com/graphql/foundation/issues/26

**Comment by mayaptos** [comment]
Last chance to comment on the blog before it posts

**Comment by benjie** [comment]
Tweaked the Querying Query query entry because it has now been discussed.

**Comment by acao** [comment]
hey sorry just coming across this! I'd like to add making vscode-graphql the official vscode plugin, and growing by 30K users in a month! @mayaptos should i just add it to the google doc?

**Comment by benjie** [comment]
@acao Yes; just add it to the doc :+1:

**Comment by acao** [comment]
done!

**Comment by Urigo** [comment]
sorry it took so long, @mayaptos I've added some things and links!
